name: Lint Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up clang-format
              run: sudo apt-get install clang-format

            - name: Check code style
              run: |
                  clang-format --version
                  find . -name "*.c" -o -name "*.h" | xargs clang-format -style=file --dry-run -Werror